name: CanvasEggGalleryApp
targets:
  iosApp:
    type: application
    platform: iOS
    deploymentTarget: "18.1"
    sources:
      - path: Sources
    info:
      path: Info.plist
    dependencies:
      - framework: Frameworks/CanvasEggGalleryKit.xcframework
        embed: true

    settings:
      PRODUCT_NAME: CanvasEggGalleryApp
      PRODUCT_BUNDLE_IDENTIFIER: io.github.honatsugiexpress.canvasegg.gallery
      CODE_SIGNING_ALLOWED: NO
      CODE_SIGNING_REQUIRED: NO
      ENTITLEMENTS_REQUIRED: NO
      GENERATE_INFOPLIST_FILE: NO
    uiTest:
      type: bundle.ui-testing
      platform: iOS
      deploymentTarget: "18.1"
      sources:
        -path: Tests/UI
      dependencies:
        - target: iosApp
      CODE_SIGNING_ALLOWED: NO
      CODE_SIGNING_REQUIRED: NO
      ENTITLEMENTS_REQUIRED: NO
      GENERATE_INFOPLIST_FILE: NO