name: Gallery iOS App Screen video

on:  workflow_dispatch

jobs:
  run-simulator:
    runs-on: macos-15
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download Artifact
        uses: dawidd6/action-download-artifact@v6
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}
          workflow: ios_build_gallery.yml
          name: CanvasEggGalleryApp
          path: ./
      - name: Boot device
        run: |
          DEVICE_ID=$(xcrun simctl list devices available | grep "iPhone 16" | grep -v "unavailable" | head -1 | sed -E 's/.*\(([-A-Z0-9]+)\).*/\1/')
          xcrun simctl boot "$DEVICE_ID"
          open -a Simulator
      - name: Install and Launch App
        run: |
          APP_PATH="CanvasEggGalleryApp.xcarchive/Products/Applications/CanvasEggGalleryApp.app"
          BUNDLE_ID="io.github.honatsugiexpress.canvasegg.gallery"
          
          xcrun simctl install booted "$APP_PATH"
          xcrun simctl launch booted "$BUNDLE_ID"
          xcrun simctl io booted recordVideo output.mp4 &
      - name: Control App
        run: |
          tap_sim() {
            osascript -e "tell application \"System Events\" to tell process \"Simulator\"
              set {x, y} to position of window 1
              click at {x + $1, y + $2}
            end tell"
          }
          sleep 2
          tap_sim 294 184
          sleep 5
      - name: Stop App
        run: |
          killall -SIGINT simctl
          sleep 10
      - name: Upload Video
        uses: actions/upload-artifact@v4
        with:
          name: ios-simulation-video
          path: output.mp4
          
