name: Gallery iOS App Screen video

on:  workflow_dispatch

jobs:
  run-simulator:
    runs-on: macos-15
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install XcodeGen
        run: |
          brew install xcodegen

      - name: Make Directory
        working-directory: canvasegg-examples/canvasegg-gallery-ios
        run: |
          mkdir -p Frameworks/CanvasEggGalleryKit.xcframework
      
      - name: Download Artifact
        uses: dawidd6/action-download-artifact@v6
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}
          workflow: ios_build_gallery.yml
          name: CanvasEggGalleryFramework
          path: canvasegg-examples/canvasegg-gallery-ios/Frameworks/CanvasEggGalleryKit.xcframework
      - name: Generate Xcode Project
        working-directory: canvasegg-examples/canvasegg-gallery-ios
        run: |
          xcodegen generate
      - name: Run test
        working-directory: canvasegg-examples/canvasegg-gallery-ios
        run: |
          DEVICE_ID=$(xcrun simctl list devices | grep "iPhone 16" | grep "Shutdown" | head -1 | awk -F '[()]' '{print $2}')
          xcrun simctl boot "$DEVICE_ID"
          xcrun simctl bootstatus "$DEVICE_ID"
          open -a Simulator
          xcrun simctl io booted recordVideo output.mp4 &
          REC_PID=$!
          xcodebuild test \
            -scheme iosApp \
            -destination "platform=iOS Simulator,id=$DEVICE_ID" \
            -only-testing:uiTest/AutoControlTest
          sleep 5
          kill -2 $REC_PID
          
          TIMEOUT=1000
          while ps -p $REC_PID > /dev/null && [ $TIMEOUT -gt 0 ]; do
            echo "Waiting for process $REC_PID to terminate... ($TIMEOUT)"
            sleep 1
            TIMEOUT=$((TIMEOUT - 1))
          done
          sleep 5
      - name: Show simulator logs
        if: failure()
        run: |
          xcrun simctl spawn booted log show --style compact --last 10m
      - name: Upload Video
        uses: actions/upload-artifact@v4
        with:
          name: ios-simulation-video
          path: canvasegg-examples/canvasegg-gallery-ios/output.mp4
          
