name: Gallery iOS App Chrome Remote desktop

on:
  workflow_dispatch:
    inputs:
      chrome_remote_desktop_code:
        description: 'Enter your Chrome Remote Desktop Code'
        required: true
        type: string

jobs:
  run-simulator:
    runs-on: macos-15
    steps:
      - name: Checkout code
        uses: actions/checkout@v4


      - name: Install Chrome Remote Desktop
        run: |
          curl -L -o chromeremotedesktop.dmg https://dl.google.com/chrome-remote-desktop/chromeremotedesktop.dmg
          sudo hdiutil attach chromeremotedesktop.dmg

          sudo installer -pkg "/Volumes/Chrome Remote Desktop Host 146.0.7680.5/Chrome Remote Desktop Host.pkg" -target /
          
          hdiutil detach "/Volumes/Chrome Remote Desktop Host 146.0.7680.5"

      - name: Setup and Start Chrome Remote Desktop
        run: |
          TARGET_PATH=$(find /Library -name "remoting_me2me_host" -type f | head -n 1)
          echo "Found binary at: $TARGET_PATH"
          sudo "/Library/PrivilegedHelperTools/ChromeRemoteDesktopHost.app/Contents/MacOS/remoting_me2me_host" \
          --name="Github Mac" \
          --code="${{ github.event.inputs.chrome_remote_desktop_code }}" \
          --redirect-url="https://remotedesktop.google.com/_/oauthredirect" \
          --pin=123456
      - name: Boot Simulator
        run: |
          UDID=$(xcrun simctl list devices available | grep "iPhone" | head -1 | awk -F '[()]' '{print $2}')
          echo "Booting device: $UDID"
          xcrun simctl boot $UDID
          open -a Simulator

      - name: Download Artifact
        uses: dawidd6/action-download-artifact@v6
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}
    
          workflow: ios_build_gallery.yml
    
          name: CanvasEggGalleryApp
    
          path: ./
      - name: Install and Launch App

        run: |
          APP_PATH="CanvasEggGalleryApp.xcarchive/Products/Applications/CanvasEggGalleryApp.app"
          BUNDLE_ID="io.github.honatsugiexpress.canvasegg.gallery"
          
          xcrun simctl install booted "$APP_PATH"
          xcrun simctl launch booted "$BUNDLE_ID"

      - name: Keep Alive
        run: |
          echo "Waiting for 4 minutes before closing..."
          sleep 240
