name: Gallery iOS App Ngrok

on:  workflow_dispatch

jobs:
  run-simulator:
    runs-on: macos-15
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Maestro
        run: |
          curl -FsSL "https://get.maestro.mobile.dev" | bash
          echo "$HOME/.maestro/bin" >> $GITHUB_PATH
          DEVICE_ID=$(xcrun simctl list devices available | grep "iPhone SE (3rd generation)" | head -n 1 | awk -F '[()]' '{print $2}')
          xcrun simctl boot $DEVICE_ID
      - name: Download Artifact
        uses: dawidd6/action-download-artifact@v6
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}
          workflow: ios_build_gallery.yml
          name: CanvasEggGalleryApp
          path: ./
      - name: Install and Launch App
        run: |
          APP_PATH="CanvasEggGalleryApp.xcarchive/Products/Applications/CanvasEggGalleryApp.app"
          BUNDLE_ID="io.github.honatsugiexpress.canvasegg.gallery"
          
          xcrun simctl install booted "$APP_PATH"
          xcrun simctl launch booted "$BUNDLE_ID"

      - name: Start Maestro Studio & Tunnel
        run: |
          maestro studio &
          
          curl -L https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-macos-amd64.tgz | tar xz
          ./cloudflared tunnel --url http://localhost:4723 --logfile tunnel.log &
          
          sleep 15
          grep -o 'https://[-a-z0-9.]*.trycloudflare.com' tunnel.log | head -n 1
      - name: Keep Alive
        run: |
          echo "Waiting for 15 minutes before closing..."
          sleep 900
