name: Gallery iOS App Ngrok

on:
  workflow_dispatch:
    inputs:
      ngrok_authtoken:
        description: 'Enter your ngrok Auth Token'
        required: true
        type: string

jobs:
  run-simulator:
    runs-on: macos-15
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install ios-bridge-cli
          brew install ngrok/ngrok/ngrok

      - name: Start iOS Bridge & Tunnel
        run: |
          ios-bridge create "iPhone 16" "18.1" --wait
          
          ios-bridge start-server --port 8000 &
          
          ngrok config add-authtoken ${{github.event.inputs.ngrok_authtoken}}
          ngrok http 8000 --log=stdout &
          
          sleep 10
          curl -s http://localhost:4040/api/tunnels | jq -r '.tunnels[0].public_url'
      - name: Keep Alive
        run: |
          echo "Waiting for 4 minutes before closing..."
          sleep 240
