name: Gallery iOS Build

on: workflow_dispatch

jobs:
  build:
    runs-on: macos-26
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'zulu'

      - name: Setup Gradle
        with:
            cache-read-only: false
      
        uses: gradle/actions/setup-gradle@v3

      - name: Make gradlew executable
        run: chmod +x gradlew

      - name: Build KMP XCFramework
        run: |
          ./gradlew :canvasegg-examples:canvasegg-gallery:assembleCanvasEggGalleryKitDebugXCFramework
            -Pkotlin.native.ignoreDisabledTargets=true


      - name: Install XcodeGen
        run: brew install xcodegen

      - name: Generate Xcode Project
        working-directory: canvasegg-examples/canvasegg-gallery-ios/
        run: |
          mkdir Frameworks
          cp -R $GITHUB_WORKSPACE/canvasegg-examples/canvasegg-gallery/build/XCFrameworks/debug/CanvasEggGalleryKit.xcframework Frameworks/
          xcodegen generate
          xcodebuild archive \
            -project CanvasEggGalleryApp.xcodeproj \
            -scheme CanvasEggGalleryApp \
            -configuration Debug \
            -archivePath build/CanvasEggGalleryApp.xcarchive \
            -sdk iphonesimulator \
            CODE_SIGNING_ALLOWED=NO \
            CODE_SIGNING_REQUIRED=NO

            mkdir -p Payload
            cp -r ./build/iosApp.xcarchive/Products/Applications/iosApp.app Payload/
            zip -r iosApp.ipa Payload

      - name: Upload XCFramework Artifact
        uses: actions/upload-artifact@v4
        with:
          name: CanvasEggGalleryApp
          path: canvasegg-examples/canvasegg-gallery-ios/build/
