name: Gallery iOS App Maestro

on:  workflow_dispatch

jobs:
  run-simulator:
    runs-on: macos-15
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Maestro
        run: |
          curl -fsSL "https://get.maestro.mobile.dev" | bash
          echo "$HOME/.maestro/bin" >> $GITHUB_PATH
          DEVICE_ID=$(xcrun simctl list devices available | grep "iPhone 16" | head -n 1 | awk -F '[()]' '{print $2}')
          xcrun simctl boot $DEVICE_ID
      - name: Download Artifact
        uses: dawidd6/action-download-artifact@v6
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}
          workflow: ios_build_gallery.yml
          name: CanvasEggGalleryApp
          path: ./
      - name: Install and Launch App
        run: |
          APP_PATH="CanvasEggGalleryApp.xcarchive/Products/Applications/CanvasEggGalleryApp.app"
          BUNDLE_ID="io.github.honatsugiexpress.canvasegg.gallery"
          
          xcrun simctl install booted "$APP_PATH"
          xcrun simctl launch booted "$BUNDLE_ID"
          sleep 30

      - name: Start Maestro Studio & Tunnel
        run: |
          maestro studio --no-window > maestro.log 2>&1 &
          MAESTRO_PID=$!

          echo "Waiting for Maestro Studio to bind to a port..."
          
          for i in {1..60}; do
            FOUND_PORT=$(lsof -nP -iTCP -sTCP:LISTEN -p $MAESTRO_PID | grep -o ':[0-9]\+' | cut -d: -f2 | head -n 1)
            
            if [ -n "$FOUND_PORT" ]; then
              echo "Successfully detected Maestro on port: $FOUND_PORT"
              CURRENT_PORT=$FOUND_PORT
              break
            fi
            
            echo "Attempt $i: Maestro not ready yet, retrying in 5s..."
            sleep 5
            
            if [ $i -eq 60 ]; then
              echo "Error: Maestro Studio failed to start within 5 minutes."
              cat maestro.log # 失敗時はログを出力
              exit 1
            fi
          done
          curl -L https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-darwin-arm64.tgz | tar xz
          
          ./cloudflared tunnel --url http://127.0.0.1:$CURRENT_PORT > tunnel.log 2>&1 &
          
          echo "Waiting for Cloudflare URL..."
          for i in {1..10}; do
            TUNNEL_URL=$(grep -o 'https://[-a-z0-9.]*.trycloudflare.com' tunnel.log | head -n 1)
            if [ -n "$TUNNEL_URL" ]; then
              echo "--------------------------------------------------"
              echo "  Maestro Studio is available at:"
              echo "  $TUNNEL_URL"
              echo "--------------------------------------------------"
              break
            fi
            sleep 3
          done
      - name: Keep Alive
        run: |
          echo "Waiting for 15 minutes before closing..."
          sleep 900
